import type { CarListing } from "../types";

export const COPILOT_RANKING_SAMPLE: CarListing[] = [
  {
    title: "Toyota Corolla Altis Hybrid Elegance",
    make: "Toyota",
    model: "Corolla Altis",
    variant: "Hybrid Elegance",
    price: 87800,
    annualDepreciation: 14910,
    coeRemainingMonths: 64,
    registrationDate: "2020-09",
    ownerCount: 2,
    serviceRecordText: "Agent maintained, inspection welcome",
    warrantyText: "6 months warranty",
  },
  {
    title: "Kia Cerato EX",
    make: "Kia",
    model: "Cerato",
    price: 82000,
    annualDepreciation: 12400,
    registrationDate: "2020-05",
    coeRemainingMonths: 65,
    ownerCount: 1,
    serviceRecordText: "Agent maintained",
    warrantyText: "12 months warranty",
    listedClaims: { nonPhv: true },
  },
  {
    title: "Honda Vezel Hybrid",
    make: "Honda",
    model: "Vezel",
    variant: "Hybrid",
    price: 93000,
    annualDepreciation: 15800,
    registrationDate: "2019-11",
    coeRemainingMonths: 58,
    ownerCount: 2,
    serviceRecordText: "Regular serviced",
  },
  {
    title: "Toyota Sienta",
    make: "Toyota",
    model: "Sienta",
    price: 86000,
    annualDepreciation: 13700,
    registrationDate: "2019-08",
    coeRemainingMonths: 54,
    ownerCount: 2,
    serviceRecordText: "Service receipts available",
    listedClaims: { nonPhv: true },
  },
  {
    title: "Toyota Vios",
    make: "Toyota",
    model: "Vios",
    price: 76000,
    annualDepreciation: 12900,
    registrationDate: "2018-12",
    coeRemainingMonths: 45,
    ownerCount: 3,
    description: "Direct owner sale",
  },
  {
    title: "Old COE Hybrid Shuttle",
    make: "Honda",
    model: "Shuttle",
    price: 70000,
    annualDepreciation: 9000,
    fuelType: "hybrid",
    registrationDate: "2014-03",
    coeRemainingMonths: 18,
    ownerCount: 5,
    isCoeCar: true,
    isOpc: true,
    description: "rental use",
  },
];
